### ISSUE TITLE
Fork frontend and connect backend fetch reference

### ISSUE THREAD

**Issue by jacob-kamminga** [AI-Sensus/label-studio#13]

**Comment by alexanderm0** [comment]
LSF -> package.json

build commands takes tag --output-path tag as described below:

    "build": "webpack --output-path ../label-studio/label_studio/frontend/dist/lsf/js",
    "watch": "webpack --output-path ../label-studio/label_studio/frontend/dist/lsf/js --watch",

**Comment by Alexanderm0** [comment]
**Label-studio frontend (LSF)**
This is a separate repository which is also open source and managed by Heartex (company behind Label-studio). It is used to keep most of the frontend development of the application separate, after which this part can either be used to integrate into custom apps or to compile a JS script for the backend to refer to. We are doing the latter since we try to maintain the features Label-studio already has.

**Why WE want LSF**
In order to customize the interface and add features to a timeseries annotation tool while maintaining functionality of Label-studio, we need to be able to customize the frontend tags. Ideally, the timeseries and video tags (or a combination thereof) are edited to feature intuitive controls which provide functionality crucial to timeseries annotation, e.g. syncing of timeseries and video.

**How LSF is integrated into backend**
When launching the backend for the first time, it seeks the frontend build file. If it is not present, the app will fetch it from the Heartex github repo and put it in the path described above. Therefore, building LSF to this same folder should reference our custom frontend to the backend if we run Label-studio.

**Solution review**
Right now, this approach requires you to have both repositories on your machine. This seemed to be a much better solution as than rewriting the fetch of the original backend. Mainly real time development using the "watch" function to constantly rebuild changes is very convenient. As with a final product, the final build can simply be kept at the backend which can then run on a server. In conclusion, the solution should be future proof.
