### ISSUE TITLE
Investigate why new label-studio commits cause tests to fail, while we did not update from the label-studio project.

### ISSUE THREAD

**Issue by jacob-kamminga** [AI-Sensus/label-studio#29]
When creating a pull request in AI-Sensus project, automated label-studio tests fail due to new commits in label-studio project, while we did not update our forked repo. What causes this?

**Comment by jacob-kamminga** [comment]
This is the commit that caused errors: 497465708e7e776b67cc61a363b2048d07beaad9

**Comment by Jessseee** [comment]
The CI/CD workflow breaks because Heartexlabs references the repository in their own organization in the workflow file while the workflow file in our fork is out of sync with their repository. For now I synced the fork with remote, but it is probably better to update these references to our own repository so it will not unexpectedly break again in the future.

https://github.com/AI-Sensus/label-studio/blob/5648ddbc91b9284630f37441bb5f9c0b88d8b7c9/.github/workflows/cicd_pipeline.yml#L84

**Comment by jacob-kamminga** [comment]
Please update project to use workflow file in AI sensus project
