### ISSUE TITLE
Add/change link on landing page "Manage activity labels"  and point this to <projectname_annotateactivies/labelingmanager>

### ISSUE THREAD

**Issue by jacob-kamminga** [AI-Sensus/label-studio#88]

**Comment by RobvdDuim** [comment]
We decided for now that the landing page is not linked to a project. So in order for this to work the user has to select a project or we have to change the landing page to being linked to project (landingpage/<int:project_id>). 

Since we focus only on the proof of concept, I suggest taking the simpler (less beautiful) choice: user selects project from dropdown

**Comment by RobvdDuim** [comment]
Described in #94
